// swift-tools-version: 6.4
import PackageDescription

let package = Package(
    name: "swift-mechanics",
    platforms: [.macOS(.v13)],
    products: [
        .library(name: "SwiftMechanics", targets: ["SwiftMechanics"]),
        .executable(name: "mechanics-core-verification", targets: ["CoreVerification"]),
        .executable(name: "mechanics-foundation-verification", targets: ["FoundationVerification"]),
    ],
    traits: [.trait(name: "EmbeddedUnicode", description: "Link matching Embedded Swift SDK Unicode data tables.")],
    targets: [
        .target(name: "SwiftMechanics",
                exclude: [
                    "Analysis/DESIGN.md",
                    "Analysis/Derivatives/ConstraintProducts/DESIGN.md",
                    "Analysis/Derivatives/DESIGN.md",
                    "Analysis/Derivatives/MechanicalSensitivities/DESIGN.md",
                    "Analysis/Derivatives/ScalarCalculus/DESIGN.md",
                    "Analysis/Derivatives/TreeTangents/DESIGN.md",
                    "Analysis/Equilibrium/Continuation/DESIGN.md",
                    "Analysis/Equilibrium/DESIGN.md",
                    "Analysis/Equilibrium/Equations/DESIGN.md",
                    "Analysis/Equilibrium/Linearization/DESIGN.md",
                    "Analysis/Equilibrium/Statics/DESIGN.md",
                    "Analysis/Observations",
                    "Analysis/Optimization/ConvexPrograms/DESIGN.md",
                    "Analysis/Optimization/DESIGN.md",
                    "Analysis/Optimization/NonlinearKKT",
                    "Analysis/Optimization/ProblemContracts/DESIGN.md",
                    "Analysis/StructuralAnalysis/Buckling/DESIGN.md",
                    "Analysis/StructuralAnalysis/DESIGN.md",
                    "Analysis/StructuralAnalysis/HarmonicResponse/DESIGN.md",
                    "Analysis/StructuralAnalysis/Pencils/DESIGN.md",
                    "Analysis/StructuralAnalysis/PhysicalModels/DESIGN.md",
                    "DESIGN.md",
                    "Exchange/Admission/DESIGN.md",
                    "Exchange/BinaryCodec/DESIGN.md",
                    "Exchange/DESIGN.md",
                    "Exchange/Schema/DESIGN.md",
                    "Execution/DESIGN.md",
                    "Execution/Hybrid/Continuation/DESIGN.md",
                    "Execution/Hybrid/DESIGN.md",
                    "Execution/Hybrid/EventEvolution/DESIGN.md",
                    "Execution/Hybrid/ImpactPorts/DESIGN.md",
                    "Execution/Hybrid/NormalImpulse/DESIGN.md",
                    "Execution/Integration/Continuation/DESIGN.md",
                    "Execution/Integration/DESIGN.md",
                    "Execution/Integration/Equations/DESIGN.md",
                    "Execution/Integration/Stepping/DESIGN.md",
                    "Execution/Runtime/Checkpoints/DESIGN.md",
                    "Execution/Runtime/DESIGN.md",
                    "Execution/Runtime/ExecutionEvidence/DESIGN.md",
                    "Execution/Runtime/Sessions/DESIGN.md",
                    "Execution/Runtime/StateRecords/DESIGN.md",
                    "Execution/Runtime/Transactions/DESIGN.md",
                    "Mathematics/Complementarity/DESIGN.md",
                    "Mathematics/Complementarity/Problem/DESIGN.md",
                    "Mathematics/Complementarity/Projection/DESIGN.md",
                    "Mathematics/Complementarity/Solve/DESIGN.md",
                    "Mathematics/Core/DESIGN.md",
                    "Mathematics/Core/Diagnostics/DESIGN.md",
                    "Mathematics/Core/Geometry/DESIGN.md",
                    "Mathematics/Core/Spatial/DESIGN.md",
                    "Mathematics/Core/Units/DESIGN.md",
                    "Mathematics/DESIGN.md",
                    "Mathematics/Nonlinear/DESIGN.md",
                    "Mathematics/Nonlinear/NonlinearSolve/DESIGN.md",
                    "Mathematics/Numerics/DESIGN.md",
                    "Mathematics/Numerics/LinearAlgebra/DESIGN.md",
                    "Mathematics/Numerics/Reduction/DESIGN.md",
                    "Mathematics/Numerics/Scaling/DESIGN.md",
                    "Mathematics/ScalarFunctions/DESIGN.md",
                    "Modeling/Compiler/Capabilities/DESIGN.md",
                    "Modeling/Compiler/CompilationRecords/DESIGN.md",
                    "Modeling/Compiler/DESIGN.md",
                    "Modeling/Compiler/Revisions/DESIGN.md",
                    "Modeling/Compiler/Validation/DESIGN.md",
                    "Modeling/DESIGN.md",
                    "Modeling/Joints/ArticulatedTrees/DESIGN.md",
                    "Modeling/Joints/DESIGN.md",
                    "Modeling/Joints/Jacobians/DESIGN.md",
                    "Modeling/Joints/JointManifolds/DESIGN.md",
                    "Modeling/Joints/KinematicAlgebra/DESIGN.md",
                    "Modeling/Machines/DESIGN.md",
                    "Modeling/Model/Bodies/DESIGN.md",
                    "Modeling/Model/Coordinates/DESIGN.md",
                    "Modeling/Model/DESIGN.md",
                    "Modeling/Model/Identity/DESIGN.md",
                    "Modeling/Model/Inertia/DESIGN.md",
                    "Modeling/Model/Representations/DESIGN.md",
                    "Physics/Actuation/Continuation/DESIGN.md",
                    "Physics/Actuation/DESIGN.md",
                    "Physics/Actuation/DriveLaws/DESIGN.md",
                    "Physics/Actuation/LumpedLaws/DESIGN.md",
                    "Physics/Actuation/Ports/DESIGN.md",
                    "Physics/Collision/DESIGN.md",
                    "Physics/Collision/Discovery/DESIGN.md",
                    "Physics/Collision/Geometry/DESIGN.md",
                    "Physics/Collision/Persistence/DESIGN.md",
                    "Physics/Collision/Shapes/DESIGN.md",
                    "Physics/Collision/Sweep/DESIGN.md",
                    "Physics/Constraints/AssemblyProjection/DESIGN.md",
                    "Physics/Constraints/CoordinateEquations/DESIGN.md",
                    "Physics/Constraints/DESIGN.md",
                    "Physics/Constraints/ScalarJointPorts/DESIGN.md",
                    "Physics/ContactLaws/DESIGN.md",
                    "Physics/ContactLaws/Impact/DESIGN.md",
                    "Physics/ContactLaws/Inputs/DESIGN.md",
                    "Physics/ContactLaws/MaterialPairs/DESIGN.md",
                    "Physics/ContactLaws/Response/DESIGN.md",
                    "Physics/ContactPatches/DESIGN.md",
                    "Physics/ContactPatches/PlanePatches/DESIGN.md",
                    "Physics/ContactPatches/PressureFields/DESIGN.md",
                    "Physics/ContactResponse/DESIGN.md",
                    "Physics/ContactResponse/ImplicitNormal/DESIGN.md",
                    "Physics/ContactResponse/WitnessPorts/DESIGN.md",
                    "Physics/DESIGN.md",
                    "Physics/DeformingContact/ContactTransactions/DESIGN.md",
                    "Physics/DeformingContact/DESIGN.md",
                    "Physics/DeformingContact/MaterialGeometry/DESIGN.md",
                    "Physics/DeformingContact/WitnessForces/DESIGN.md",
                    "Physics/Dynamics/DESIGN.md",
                    "Physics/Dynamics/DenseDynamics/DESIGN.md",
                    "Physics/Dynamics/RigidEquations/DESIGN.md",
                    "Physics/Flexible/Beams/DESIGN.md",
                    "Physics/Flexible/DESIGN.md",
                    "Physics/Flexible/Mesh/DESIGN.md",
                    "Physics/Flexible/Tetrahedra/DESIGN.md",
                    "Physics/Fluids/ChannelDiscretization/DESIGN.md",
                    "Physics/Fluids/Continuation/DESIGN.md",
                    "Physics/Fluids/DESIGN.md",
                    "Physics/Fluids/PlanarContinuation/DESIGN.md",
                    "Physics/Fluids/PlanarProjection/DESIGN.md",
                    "Physics/Fluids/ViscousEvolution/DESIGN.md",
                    "Physics/Granular/DESIGN.md",
                    "Physics/Granular/NeighborContacts/DESIGN.md",
                    "Physics/Granular/ParticleEvolution/DESIGN.md",
                    "Physics/Granular/ParticleState/DESIGN.md",
                    "Physics/Granular/Replay/DESIGN.md",
                    "Physics/Loads/CableRouting/DESIGN.md",
                    "Physics/Loads/CustomLaws/DESIGN.md",
                    "Physics/Loads/DESIGN.md",
                    "Physics/Loads/ForcePorts/DESIGN.md",
                    "Physics/Loads/PassiveLaws/DESIGN.md",
                    "Physics/Materials/Constitutive/DESIGN.md",
                    "Physics/Materials/DESIGN.md",
                    "Physics/Materials/Elasticity/DESIGN.md",
                    "Physics/Materials/Plasticity/DESIGN.md",
                    "Physics/Mechanisms/AcceptedTransitions/DESIGN.md",
                    "Physics/Mechanisms/AffineEvolution/DESIGN.md",
                    "Physics/Mechanisms/ConnectedSleep/DESIGN.md",
                    "Physics/Mechanisms/ConstrainedDynamics/DESIGN.md",
                    "Physics/Mechanisms/NonlinearEvolution/DESIGN.md",
                    "Physics/Mechanisms/ReactionPaths/DESIGN.md",
                    "Physics/Mechanisms/SleepContinuation/DESIGN.md",
                    "Physics/Mechanisms/DESIGN.md",
                    "Physics/Transmissions/CompliantPorts/DESIGN.md",
                    "Physics/Transmissions/DESIGN.md",
                    "Physics/Transmissions/IdealNetworks/DESIGN.md",
                    "Physics/Transmissions/PortBindings/DESIGN.md",
                ],
                linkerSettings: [.linkedLibrary("swiftUnicodeDataTables", .when(platforms: [.wasi], traits: ["EmbeddedUnicode"]))]),
        .executableTarget(name: "CoreVerification", dependencies: ["SwiftMechanics"], path: "Verification/CoreVerification", exclude: ["DESIGN.md"]),
        .executableTarget(name: "FoundationVerification", dependencies: ["SwiftMechanics"], path: "Verification/FoundationVerification", exclude: ["DESIGN.md", "ObservationProbeContext.swift", "ObservationVerification.swift"]),
        .testTarget(name: "MechanicsCoreTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsModelTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsMaterialsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsNumericsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsNonlinearTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsComplementarityTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsJointsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsLoadsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsCompilerTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsCollisionTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsDynamicsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsFlexibleTests", dependencies: ["SwiftMechanics"], exclude: ["Beams/DESIGN.md", "DESIGN.md"]),
        .testTarget(name: "MechanicsContactLawsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsRuntimeTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsContactResponseTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsIntegrationTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsConstraintsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsActuationTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsHybridTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsTransmissionsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsEquilibriumTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsContactPatchesTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsDeformingContactTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsStructuralAnalysisTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsDerivativesTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsFluidsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsMechanismsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsNonlinearMechanismTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsSleepMechanismTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsReactionPathTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsGranularTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsFluidsRuntimeTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsFluidsProjectionTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsOptimizationTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsExchangeTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "SwiftMechanicsMachineTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
    ],
    swiftLanguageModes: [.v6]
)
