// swift-tools-version: 6.4
import PackageDescription

let package = Package(
    name: "swift-mechanics",
    platforms: [.macOS(.v13)],
    products: [
        .library(name: "SwiftMechanics", targets: ["MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsMaterials", "MechanicsNonlinear", "MechanicsComplementarity", "MechanicsJoints", "MechanicsLoads", "MechanicsCompiler", "MechanicsCollision", "MechanicsDynamics", "MechanicsFlexible", "MechanicsContactLaws", "MechanicsRuntime", "MechanicsContactResponse", "MechanicsIntegration", "MechanicsExchange", "MechanicsConstraints", "MechanicsActuation", "MechanicsHybrid", "MechanicsTransmissions", "MechanicsEquilibrium", "MechanicsContactPatches", "MechanicsDeformingContact", "MechanicsStructuralAnalysis"]),
        .library(name: "MechanicsCore", targets: ["MechanicsCore"]),
        .library(name: "MechanicsModel", targets: ["MechanicsModel"]),
        .library(name: "MechanicsNumerics", targets: ["MechanicsNumerics"]),
        .library(name: "MechanicsMaterials", targets: ["MechanicsMaterials"]),
        .library(name: "MechanicsNonlinear", targets: ["MechanicsNonlinear"]),
        .library(name: "MechanicsComplementarity", targets: ["MechanicsComplementarity"]),
        .library(name: "MechanicsJoints", targets: ["MechanicsJoints"]),
        .library(name: "MechanicsLoads", targets: ["MechanicsLoads"]),
        .library(name: "MechanicsCompiler", targets: ["MechanicsCompiler"]),
        .library(name: "MechanicsCollision", targets: ["MechanicsCollision"]),
        .library(name: "MechanicsDynamics", targets: ["MechanicsDynamics"]),
        .library(name: "MechanicsFlexible", targets: ["MechanicsFlexible"]),
        .library(name: "MechanicsContactLaws", targets: ["MechanicsContactLaws"]),
        .library(name: "MechanicsRuntime", targets: ["MechanicsRuntime"]),
        .library(name: "MechanicsContactResponse", targets: ["MechanicsContactResponse"]),
        .library(name: "MechanicsIntegration", targets: ["MechanicsIntegration"]),
        .library(name: "MechanicsExchange", targets: ["MechanicsExchange"]),
        .library(name: "MechanicsConstraints", targets: ["MechanicsConstraints"]),
        .library(name: "MechanicsActuation", targets: ["MechanicsActuation"]),
        .library(name: "MechanicsHybrid", targets: ["MechanicsHybrid"]),
        .library(name: "MechanicsTransmissions", targets: ["MechanicsTransmissions"]),
        .library(name: "MechanicsEquilibrium", targets: ["MechanicsEquilibrium"]),
        .library(name: "MechanicsContactPatches", targets: ["MechanicsContactPatches"]),
        .library(name: "MechanicsDeformingContact", targets: ["MechanicsDeformingContact"]),
        .library(name: "MechanicsStructuralAnalysis", targets: ["MechanicsStructuralAnalysis"]),
        .executable(name: "mechanics-core-verification", targets: ["CoreVerification"]),
        .executable(name: "mechanics-foundation-verification", targets: ["FoundationVerification"]),
    ],
    traits: [.trait(name: "EmbeddedUnicode", description: "Link matching Embedded Swift SDK Unicode data tables.")],
    targets: [
        .target(
            name: "CMechanicsMath",
            exclude: ["DESIGN.md"],
            linkerSettings: [.linkedLibrary("m", .when(platforms: [.linux]))]
        ),
        .target(name: "MechanicsCore", dependencies: ["CMechanicsMath"],
                exclude: ["DESIGN.md", "Diagnostics/DESIGN.md", "Geometry/DESIGN.md", "Spatial/DESIGN.md", "Units/DESIGN.md"],
                linkerSettings: [.linkedLibrary("swiftUnicodeDataTables", .when(platforms: [.wasi], traits: ["EmbeddedUnicode"]))]),
        .target(name: "MechanicsModel", dependencies: ["MechanicsCore"],
                exclude: ["DESIGN.md", "Identity/DESIGN.md", "Representations/DESIGN.md", "Inertia/DESIGN.md", "Bodies/DESIGN.md", "Coordinates/DESIGN.md"]),
        .target(name: "MechanicsNumerics", dependencies: ["MechanicsCore"],
                exclude: ["DESIGN.md", "LinearAlgebra/DESIGN.md", "Scaling/DESIGN.md", "Reduction/DESIGN.md"]),
        .target(name: "MechanicsMaterials", dependencies: ["MechanicsCore"],
                exclude: ["DESIGN.md", "Constitutive/DESIGN.md", "Elasticity/DESIGN.md", "Plasticity/DESIGN.md"]),
        .target(name: "MechanicsNonlinear", dependencies: ["MechanicsNumerics"],
                exclude: ["DESIGN.md", "NonlinearSolve/DESIGN.md"]),
        .target(name: "MechanicsComplementarity", dependencies: ["MechanicsNumerics"],
                exclude: ["DESIGN.md", "Problem/DESIGN.md", "Projection/DESIGN.md", "Solve/DESIGN.md"]),
        .target(name: "MechanicsJoints", dependencies: ["MechanicsCore", "MechanicsModel"],
                exclude: ["DESIGN.md", "KinematicAlgebra/DESIGN.md", "JointManifolds/DESIGN.md", "ArticulatedTrees/DESIGN.md", "Jacobians/DESIGN.md"]),
        .target(name: "MechanicsLoads", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsJoints"],
                exclude: ["DESIGN.md", "ForcePorts/DESIGN.md", "PassiveLaws/DESIGN.md", "CableRouting/DESIGN.md", "CustomLaws/DESIGN.md"]),
        .target(name: "MechanicsCompiler", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsJoints"],
                exclude: ["DESIGN.md", "CompilationRecords/DESIGN.md", "Capabilities/DESIGN.md", "Validation/DESIGN.md", "Revisions/DESIGN.md"]),
        .target(name: "MechanicsCollision", dependencies: ["MechanicsCore", "MechanicsModel"],
                exclude: ["DESIGN.md", "Shapes/DESIGN.md", "Geometry/DESIGN.md", "Discovery/DESIGN.md", "Persistence/DESIGN.md", "Sweep/DESIGN.md"]),
        .target(name: "MechanicsDynamics", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsJoints", "MechanicsLoads"],
                exclude: ["DESIGN.md", "RigidEquations/DESIGN.md", "DenseDynamics/DESIGN.md"]),
        .target(name: "MechanicsFlexible", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsMaterials"],
                exclude: ["DESIGN.md", "Mesh/DESIGN.md", "Tetrahedra/DESIGN.md", "Beams/DESIGN.md"]),
        .target(name: "MechanicsContactLaws", dependencies: ["MechanicsCore", "MechanicsModel"],
                exclude: ["DESIGN.md", "Inputs/DESIGN.md", "MaterialPairs/DESIGN.md", "Response/DESIGN.md", "Impact/DESIGN.md"]),
        .target(name: "MechanicsRuntime", dependencies: ["MechanicsCompiler", "MechanicsJoints"],
                exclude: ["DESIGN.md", "StateRecords/DESIGN.md", "Transactions/DESIGN.md", "Checkpoints/DESIGN.md", "Sessions/DESIGN.md", "ExecutionEvidence/DESIGN.md"]),
        .target(name: "MechanicsContactResponse", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsJoints", "MechanicsDynamics", "MechanicsCollision", "MechanicsContactLaws", "MechanicsComplementarity"],
                exclude: ["DESIGN.md", "WitnessPorts/DESIGN.md", "ImplicitNormal/DESIGN.md"]),
        .target(name: "MechanicsIntegration", dependencies: ["MechanicsCore", "MechanicsCompiler", "MechanicsJoints", "MechanicsNumerics", "MechanicsRuntime"],
                exclude: ["DESIGN.md", "Equations/DESIGN.md", "Continuation/DESIGN.md", "Stepping/DESIGN.md"]),
        .target(name: "MechanicsExchange", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsJoints", "MechanicsCompiler"],
                exclude: ["DESIGN.md", "Schema/DESIGN.md", "BinaryCodec/DESIGN.md", "Admission/DESIGN.md"]),
        .target(name: "MechanicsConstraints", dependencies: ["MechanicsCore", "MechanicsNumerics", "MechanicsNonlinear", "MechanicsJoints", "CMechanicsMath"],
                exclude: ["DESIGN.md", "CoordinateEquations/DESIGN.md", "AssemblyProjection/DESIGN.md", "ScalarJointPorts/DESIGN.md"]),
        .target(name: "MechanicsActuation", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsJoints", "MechanicsCompiler", "MechanicsLoads", "MechanicsRuntime"],
                exclude: ["DESIGN.md", "Ports/DESIGN.md", "DriveLaws/DESIGN.md", "LumpedLaws/DESIGN.md", "Continuation/DESIGN.md"]),
        .target(name: "MechanicsHybrid", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsJoints", "MechanicsCompiler", "MechanicsLoads", "MechanicsDynamics", "MechanicsCollision", "MechanicsContactLaws", "MechanicsRuntime", "MechanicsIntegration"],
                exclude: ["DESIGN.md", "ImpactPorts/DESIGN.md", "NormalImpulse/DESIGN.md", "EventEvolution/DESIGN.md", "Continuation/DESIGN.md"]),
        .target(name: "MechanicsTransmissions", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsJoints", "MechanicsNumerics", "MechanicsConstraints", "MechanicsNonlinear"],
                exclude: ["DESIGN.md", "PortBindings/DESIGN.md", "IdealNetworks/DESIGN.md", "CompliantPorts/DESIGN.md"]),
        .target(name: "MechanicsEquilibrium", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsNonlinear", "MechanicsConstraints", "MechanicsJoints", "MechanicsCompiler", "MechanicsLoads", "MechanicsDynamics", "CMechanicsMath"],
                exclude: ["DESIGN.md", "Equations/DESIGN.md", "Statics/DESIGN.md", "Linearization/DESIGN.md", "Continuation/DESIGN.md"]),
        .target(name: "MechanicsContactPatches", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsFlexible"],
                exclude: ["DESIGN.md", "PressureFields/DESIGN.md", "PlanePatches/DESIGN.md"]),
        .target(name: "MechanicsDeformingContact", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsFlexible", "MechanicsCollision", "MechanicsContactLaws"],
                exclude: ["DESIGN.md", "MaterialGeometry/DESIGN.md", "WitnessForces/DESIGN.md", "ContactTransactions/DESIGN.md"]),
        .target(name: "MechanicsStructuralAnalysis", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsMaterials", "MechanicsNumerics", "MechanicsCompiler", "MechanicsEquilibrium", "MechanicsFlexible", "CMechanicsMath"],
                exclude: ["DESIGN.md", "PhysicalModels/DESIGN.md", "Pencils/DESIGN.md", "HarmonicResponse/DESIGN.md", "Buckling/DESIGN.md"]),
        .executableTarget(name: "CoreVerification", dependencies: ["MechanicsCore"], exclude: ["DESIGN.md"]),
        .executableTarget(name: "FoundationVerification", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsMaterials", "MechanicsNonlinear", "MechanicsComplementarity", "MechanicsJoints", "MechanicsLoads", "MechanicsCompiler", "MechanicsCollision", "MechanicsDynamics", "MechanicsFlexible", "MechanicsContactLaws", "MechanicsRuntime", "MechanicsContactResponse", "MechanicsIntegration", "MechanicsExchange", "MechanicsConstraints", "MechanicsActuation", "MechanicsHybrid", "MechanicsTransmissions", "MechanicsEquilibrium", "MechanicsContactPatches", "MechanicsDeformingContact", "MechanicsStructuralAnalysis"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsCoreTests", dependencies: ["MechanicsCore"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsModelTests", dependencies: ["MechanicsModel", "MechanicsCore"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsMaterialsTests", dependencies: ["MechanicsMaterials", "MechanicsCore"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsNumericsTests", dependencies: ["MechanicsNumerics", "MechanicsCore"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsNonlinearTests", dependencies: ["MechanicsNonlinear", "MechanicsNumerics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsComplementarityTests", dependencies: ["MechanicsComplementarity", "MechanicsNumerics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsJointsTests", dependencies: ["MechanicsJoints", "MechanicsCore", "MechanicsModel"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsLoadsTests", dependencies: ["MechanicsLoads", "MechanicsCore", "MechanicsModel", "MechanicsJoints"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsCompilerTests", dependencies: ["MechanicsCompiler", "MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsJoints"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsCollisionTests", dependencies: ["MechanicsCollision", "MechanicsCore", "MechanicsModel"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsDynamicsTests", dependencies: ["MechanicsDynamics", "MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsJoints", "MechanicsLoads"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsFlexibleTests", dependencies: ["MechanicsFlexible", "MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsMaterials"], exclude: ["DESIGN.md", "Beams/DESIGN.md"]),
        .testTarget(name: "MechanicsContactLawsTests", dependencies: ["MechanicsContactLaws", "MechanicsCore", "MechanicsModel"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsRuntimeTests", dependencies: ["MechanicsRuntime", "MechanicsCompiler", "MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsJoints"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsContactResponseTests", dependencies: ["MechanicsContactResponse", "MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsJoints", "MechanicsLoads", "MechanicsDynamics", "MechanicsCollision", "MechanicsContactLaws", "MechanicsComplementarity"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsIntegrationTests", dependencies: ["MechanicsIntegration", "MechanicsCore", "MechanicsCompiler", "MechanicsJoints", "MechanicsNumerics", "MechanicsRuntime", "MechanicsModel"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsConstraintsTests", dependencies: ["MechanicsConstraints", "MechanicsCore", "MechanicsNumerics", "MechanicsNonlinear", "MechanicsJoints", "CMechanicsMath"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsActuationTests", dependencies: ["MechanicsActuation", "MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsJoints", "MechanicsCompiler", "MechanicsLoads", "MechanicsRuntime"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsHybridTests", dependencies: ["MechanicsHybrid", "MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsJoints", "MechanicsCompiler", "MechanicsLoads", "MechanicsDynamics", "MechanicsCollision", "MechanicsContactLaws", "MechanicsRuntime", "MechanicsIntegration"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsTransmissionsTests", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsJoints", "MechanicsNumerics", "MechanicsConstraints", "MechanicsNonlinear", "MechanicsTransmissions"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsEquilibriumTests", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsNonlinear", "MechanicsConstraints", "MechanicsJoints", "MechanicsCompiler", "MechanicsLoads", "MechanicsDynamics", "CMechanicsMath", "MechanicsEquilibrium"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsContactPatchesTests", dependencies: ["MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsFlexible", "MechanicsContactPatches", "MechanicsMaterials"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsDeformingContactTests", dependencies: ["MechanicsDeformingContact", "MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsFlexible", "MechanicsMaterials", "MechanicsCollision", "MechanicsContactLaws"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsStructuralAnalysisTests", dependencies: ["MechanicsStructuralAnalysis", "MechanicsCore", "MechanicsModel", "MechanicsMaterials", "MechanicsNumerics", "MechanicsCompiler", "MechanicsEquilibrium", "MechanicsFlexible", "MechanicsNonlinear", "MechanicsConstraints", "MechanicsJoints", "MechanicsLoads", "MechanicsDynamics", "CMechanicsMath"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsExchangeTests", dependencies: ["MechanicsExchange", "MechanicsCore", "MechanicsModel", "MechanicsNumerics", "MechanicsJoints", "MechanicsCompiler"], exclude: ["DESIGN.md"]),
    ],
    swiftLanguageModes: [.v6]
)
