// swift-tools-version: 6.4
import PackageDescription

let package = Package(
    name: "swift-mechanics",
    platforms: [.macOS(.v13)],
    products: [
        .executable(name: "mechanics-spatial-beams-verification", targets: ["SpatialBeamsPublicVerification"]),
        .executable(name: "mechanics-hydroelastic-verification", targets: ["HydroelasticPublicVerification"]),
        .executable(name: "mechanics-compound-queries-verification", targets: ["CompoundQueriesPublicVerification"]),
        .executable(name: "mechanics-triangle-meshes-verification", targets: ["TriangleMeshesPublicVerification"]),
        .executable(name: "mechanics-particle-flows-verification", targets: ["ParticleFlowsPublicVerification"]),
        .executable(name: "mechanics-spatial-projection-verification", targets: ["SpatialProjectionPublicVerification"]),
        .executable(name: "modal-reduction-verification", targets: ["ModalReductionQualification"]),
        .executable(name: "mechanics-inertial-parameters-verification", targets: ["InertialParametersPublicVerification"]),
        .executable(name: "mechanics-linear-estimation-verification", targets: ["LinearEstimationPublicVerification"]),
        .executable(name: "mechanics-nonlinear-estimation-verification", targets: ["NonlinearEstimationPublicVerification"]),
        .executable(name: "mechanics-structural-authoring-verification", targets: ["StructuralAuthoringPublicVerification"]),
        .executable(name: "mechanics-tire-laws-verification", targets: ["TireLawsPublicVerification"]),
        .executable(name: "mechanics-vehicle-laws-verification", targets: ["VehicleLawsPublicVerification"]),
        .library(name: "SwiftMechanics", targets: ["SwiftMechanics"]),
        .executable(name: "mechanics-sdf-verification", targets: ["SDFPublicVerification"]),
        .executable(name: "mechanics-core-verification", targets: ["CoreVerification"]),
        .executable(name: "mechanics-foundation-verification", targets: ["FoundationVerification"]),
    ],
    traits: [.trait(name: "EmbeddedUnicode", description: "Link matching Embedded Swift SDK Unicode data tables.")],
    targets: [
        .target(name: "CompoundQueriesQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/CompoundQueriesQualification",
                    exclude: ["DESIGN.md", "CompoundQueriesQualification.swift", "CompoundQueriesQualificationTests.swift"], sources: ["CompoundQueriesQualificationCases.swift", "CompoundQueriesQualificationError.swift", "CompoundQueriesQualificationFixture.swift", "CompoundQueriesQualificationUnexpectedFilter.swift"]),
        .executableTarget(name: "CompoundQueriesPublicVerification", dependencies: ["CompoundQueriesQualificationSupport"], path: "Verification/CompoundQueriesQualification",
                    exclude: ["DESIGN.md", "CompoundQueriesQualificationCases.swift", "CompoundQueriesQualificationError.swift", "CompoundQueriesQualificationFixture.swift", "CompoundQueriesQualificationUnexpectedFilter.swift", "CompoundQueriesQualificationTests.swift"], sources: ["CompoundQueriesQualification.swift"]),
        .testTarget(name: "MechanicsCompoundQueriesTests", dependencies: ["SwiftMechanics", "CompoundQueriesQualificationSupport"], path: "Verification/CompoundQueriesQualification",
                    exclude: ["DESIGN.md", "CompoundQueriesQualificationCases.swift", "CompoundQueriesQualificationError.swift", "CompoundQueriesQualificationFixture.swift", "CompoundQueriesQualificationUnexpectedFilter.swift", "CompoundQueriesQualification.swift"], sources: ["CompoundQueriesQualificationTests.swift"]),
        .target(name: "ModalReductionQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/ModalReductionQualification", exclude: ["DESIGN.md", "ModalReductionQualification.swift", "ModalReductionQualificationTests.swift"], sources: ["ModalReductionCancellationCounter.swift", "ModalReductionQualificationCase.swift", "ModalReductionQualificationCases.swift", "ModalReductionQualificationError.swift", "ModalReductionQualificationFixtures.swift", "ModalReductionQualifying.swift"]),
        .executableTarget(name: "ModalReductionQualification", dependencies: ["SwiftMechanics", "ModalReductionQualificationSupport"], path: "Verification/ModalReductionQualification", exclude: ["DESIGN.md", "ModalReductionQualificationTests.swift", "ModalReductionCancellationCounter.swift", "ModalReductionQualificationCase.swift", "ModalReductionQualificationCases.swift", "ModalReductionQualificationError.swift", "ModalReductionQualificationFixtures.swift", "ModalReductionQualifying.swift"], sources: ["ModalReductionQualification.swift"]),
        .testTarget(name: "ModalReductionQualificationTests", dependencies: ["SwiftMechanics", "ModalReductionQualificationSupport"], path: "Verification/ModalReductionQualification", exclude: ["DESIGN.md", "ModalReductionQualification.swift", "ModalReductionCancellationCounter.swift", "ModalReductionQualificationCase.swift", "ModalReductionQualificationCases.swift", "ModalReductionQualificationError.swift", "ModalReductionQualificationFixtures.swift", "ModalReductionQualifying.swift"], sources: ["ModalReductionQualificationTests.swift"]),

        .target(name: "InertialParametersQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/InertialParametersQualification",
                    exclude: ["DESIGN.md", "InertialParametersQualification.swift", "InertialParametersQualificationTests.swift"], sources: ["InertialParametersQualificationCancellation.swift", "InertialParametersQualificationCases.swift", "InertialParametersQualificationError.swift", "InertialParametersQualificationFixture.swift", "InertialParametersQualificationOracle.swift"]),
        .executableTarget(name: "InertialParametersPublicVerification", dependencies: ["InertialParametersQualificationSupport"], path: "Verification/InertialParametersQualification",
                    exclude: ["DESIGN.md", "InertialParametersQualificationCancellation.swift", "InertialParametersQualificationCases.swift", "InertialParametersQualificationError.swift", "InertialParametersQualificationFixture.swift", "InertialParametersQualificationOracle.swift", "InertialParametersQualificationTests.swift"], sources: ["InertialParametersQualification.swift"]),
        .testTarget(name: "MechanicsInertialParametersTests", dependencies: ["SwiftMechanics", "InertialParametersQualificationSupport"], path: "Verification/InertialParametersQualification",
                    exclude: ["DESIGN.md", "InertialParametersQualificationCancellation.swift", "InertialParametersQualificationCases.swift", "InertialParametersQualificationError.swift", "InertialParametersQualificationFixture.swift", "InertialParametersQualificationOracle.swift", "InertialParametersQualification.swift"], sources: ["InertialParametersQualificationTests.swift"]),
        .target(name: "SwiftMechanics",
                exclude: [
                    "Physics/Flexible/SpatialBeams/DESIGN.md",
                    "Physics/Collision/CompoundQueries/DESIGN.md",
                    "Physics/Collision/TriangleMeshes/DESIGN.md",
                    "Physics/Fluids/ParticleFlows/DESIGN.md",
                "Physics/Flexible/ModalReduction/DESIGN.md",
                    "Analysis/Derivatives/InertialParameters/DESIGN.md",
                    "Execution/Control/LinearEstimation/DESIGN.md",
                    "Execution/Control/NonlinearEstimation/DESIGN.md",
                    "Physics/Vehicles/TerrainLaws/DESIGN.md",
                    "Analysis/Derivatives/GeometryParameters/DESIGN.md",
                    "Physics/Flexible/FieldOutputs/DESIGN.md",
                    "Physics/Dynamics/ArticulatedDynamics/DESIGN.md",
                    "Modeling/Machines/StructuralAuthoring/DESIGN.md",
                    "Analysis/Planning/TimeParameterization/DESIGN.md",
                    "Analysis/Planning/PoseIK/DESIGN.md",
                    "Analysis/Planning/DESIGN.md",
                    "Physics/Constraints/RollingRelations/DESIGN.md",
                    "Physics/Vehicles/TireLaws/DESIGN.md",
                    "Physics/Vehicles/DESIGN.md",
                    "Execution/Control/TaskSpace/DESIGN.md",
                    "Exchange/URDF/DESIGN.md",
                    "Physics/Loads/AffineRigidGravity/DESIGN.md",
                    "Execution/Control/ExternalCommands/DESIGN.md",
                    "Analysis/Optimization/LinearPrograms/DESIGN.md",                    "Physics/Loads/SphereHydrostatics/DESIGN.md",
                    "Physics/Loads/DirectionalHydrodynamics/DESIGN.md",
                    "Physics/Loads/AerodynamicPolars/DESIGN.md",
                    "Physics/Loads/FollowerPressure/DESIGN.md",
                    "Physics/Loads/HarmonicGravity/DESIGN.md",
                    "Physics/Constraints/JointStops/DESIGN.md",
                    "Exchange/SDF/DESIGN.md",
                    "Exchange/XML/DESIGN.md", "Exchange/MJCF/DESIGN.md", "Analysis/Derivatives/TreeTangents/Planar",
                    "Analysis/Observations/ContactRangeObservations/DESIGN.md",
                    "Analysis/Observations/SensorPipeline/DESIGN.md",
                    "Execution/Control/Continuation/DESIGN.md",
                    "Execution/Control/DESIGN.md",
                    "Execution/Control/MechanicalPlant/DESIGN.md",
                    "Execution/Control/Ports/DESIGN.md",
                    "Execution/Control/SampledFeedback/DESIGN.md",
                    "Physics/Mechanisms/StationaryIslandDynamics/DESIGN.md",
                    "Physics/Mechanisms/IslandSleepContinuation",
                    "Execution/Hybrid/ConstrainedSleepEvolution",
                    "Analysis/DESIGN.md",
                    "Analysis/Derivatives/ConstraintProducts/DESIGN.md",
                    "Analysis/Derivatives/DESIGN.md",
                    "Analysis/Derivatives/ContactProducts/DESIGN.md",
                    "Analysis/Derivatives/MechanicalSensitivities/DESIGN.md",
                    "Analysis/Derivatives/ScalarCalculus/DESIGN.md",
                    "Analysis/Derivatives/TreeTangents/DESIGN.md",
                    "Analysis/Equilibrium/Continuation/DESIGN.md",
                    "Analysis/Equilibrium/DESIGN.md",
                    "Analysis/Equilibrium/Equations/DESIGN.md",
                    "Analysis/Equilibrium/Linearization/DESIGN.md",
                    "Analysis/Equilibrium/Statics/DESIGN.md",
                    "Analysis/Observations/DESIGN.md",
                    "Analysis/Observations/ObservationRecords/DESIGN.md",
                    "Analysis/Observations/KinematicObservations/DESIGN.md",
                    "Analysis/Observations/InertialObservations/DESIGN.md",
                    "Analysis/Observations/WrenchObservations/DESIGN.md",
                    "Analysis/Optimization/ConvexPrograms/DESIGN.md",
                    "Analysis/Optimization/DESIGN.md",
                    "Analysis/Optimization/ParameterIdentification/DESIGN.md",
                    "Analysis/Optimization/NonlinearKKT/DESIGN.md",
                    "Analysis/Optimization/ProblemContracts/DESIGN.md",
                    "Analysis/StructuralAnalysis/Buckling/DESIGN.md",
                    "Analysis/StructuralAnalysis/DESIGN.md",
                    "Analysis/StructuralAnalysis/GeneralDampedSpectrum/DESIGN.md",
                    "Analysis/StructuralAnalysis/NonlinearStability/DESIGN.md",
                    "Analysis/StructuralAnalysis/HarmonicResponse/DESIGN.md",
                    "Analysis/StructuralAnalysis/Pencils/DESIGN.md",
                    "Analysis/StructuralAnalysis/PhysicalModels/DESIGN.md",
                    "DESIGN.md",
                    "Exchange/Admission/DESIGN.md",
                    "Exchange/BinaryCodec/DESIGN.md",
                    "Exchange/DESIGN.md",
                    "Exchange/Schema/DESIGN.md",
                    "Execution/DESIGN.md",
                    "Execution/Hybrid/Continuation/DESIGN.md",
                    "Execution/Hybrid/DESIGN.md",
                    "Execution/Hybrid/FrictionalImpulse/DESIGN.md",
                    "Execution/Hybrid/ConstrainedNormalImpulse/DESIGN.md",
                    "Execution/Hybrid/EventEvolution/DESIGN.md",
                    "Execution/Hybrid/ImpactPorts/DESIGN.md",
                    "Execution/Hybrid/NormalImpulse/DESIGN.md",
                    "Execution/Integration/Continuation/DESIGN.md",
                    "Execution/Integration/DESIGN.md",
                    "Execution/Integration/Equations/DESIGN.md",
                    "Execution/Integration/Stepping/DESIGN.md",
                    "Execution/Runtime/Checkpoints/DESIGN.md",
                    "Execution/Runtime/DESIGN.md",
                    "Execution/Runtime/ExecutionEvidence/DESIGN.md",
                    "Execution/Runtime/Sessions/DESIGN.md",
                    "Execution/Runtime/StateRecords/DESIGN.md",
                    "Execution/Runtime/Transactions/DESIGN.md",
                    "Mathematics/Complementarity/DESIGN.md",
                    "Mathematics/Complementarity/Problem/DESIGN.md",
                    "Mathematics/Complementarity/Projection/DESIGN.md",
                    "Mathematics/Complementarity/Solve/DESIGN.md",
                    "Mathematics/Core/DESIGN.md",
                    "Mathematics/Core/Diagnostics/DESIGN.md",
                    "Mathematics/Core/Geometry/DESIGN.md",
                    "Mathematics/Core/Spatial/DESIGN.md",
                    "Mathematics/Core/Units/DESIGN.md",
                    "Mathematics/DESIGN.md",
                    "Mathematics/Nonlinear/DESIGN.md",
                    "Mathematics/Nonlinear/NonlinearSolve/DESIGN.md",
                    "Mathematics/Numerics/DESIGN.md",
                    "Mathematics/Numerics/ComplexSpectrum/DESIGN.md",
                    "Mathematics/Numerics/LinearAlgebra/DESIGN.md",
                    "Mathematics/Numerics/Reduction/DESIGN.md",
                    "Mathematics/Numerics/Scaling/DESIGN.md",
                    "Mathematics/ScalarFunctions/DESIGN.md",
                    "Modeling/Compiler/Capabilities/DESIGN.md",
                    "Modeling/Compiler/CompilationRecords/DESIGN.md",
                    "Modeling/Compiler/DESIGN.md",
                    "Modeling/Compiler/Revisions/DESIGN.md",
                    "Modeling/Compiler/Validation/DESIGN.md",
                    "Modeling/DESIGN.md",
                    "Modeling/Joints/ArticulatedTrees/DESIGN.md",
                    "Modeling/Joints/DESIGN.md",
                    "Modeling/Joints/Jacobians/DESIGN.md",
                    "Modeling/Joints/JointManifolds/DESIGN.md",
                    "Modeling/Joints/KinematicAlgebra/DESIGN.md",
                    "Modeling/Joints/PrescribedMotions/DESIGN.md",
                    "Modeling/Machines/DESIGN.md",
                    "Modeling/Model/Bodies/DESIGN.md",
                    "Modeling/Model/Coordinates/DESIGN.md",
                    "Modeling/Model/DESIGN.md",
                    "Modeling/Model/Identity/DESIGN.md",
                    "Modeling/Model/Inertia/DESIGN.md",
                    "Modeling/Model/Representations/DESIGN.md",
                    "Physics/Actuation/Continuation/DESIGN.md",
                    "Physics/Actuation/DESIGN.md",
                    "Physics/Actuation/DriveLaws/DESIGN.md",
                    "Physics/Actuation/LumpedLaws/DESIGN.md",
                    "Physics/Actuation/Ports/DESIGN.md",
                    "Physics/Collision/DESIGN.md",
                    "Physics/Collision/ConvexQueries/DESIGN.md",
                    "Physics/Collision/Discovery/DESIGN.md",
                    "Physics/Collision/Geometry/DESIGN.md",
                    "Physics/Collision/Persistence/DESIGN.md",
                    "Physics/Collision/Shapes/DESIGN.md",
                    "Physics/Collision/Sweep/DESIGN.md",
                    "Physics/Constraints/AssemblyProjection/DESIGN.md",
                    "Physics/Constraints/CoordinateEquations/DESIGN.md",
                    "Physics/Constraints/DESIGN.md",
                    "Physics/Constraints/GeometricRelations/DESIGN.md",
                    "Physics/Constraints/ManifoldProjection/DESIGN.md",
                    "Physics/Constraints/ScalarJointPorts/DESIGN.md",
                    "Physics/ContactLaws/DESIGN.md",
                    "Physics/ContactLaws/Impact/DESIGN.md",
                    "Physics/ContactLaws/Inputs/DESIGN.md",
                    "Physics/ContactLaws/MaterialPairs/DESIGN.md",
                    "Physics/ContactLaws/Response/DESIGN.md",
                    "Physics/ContactLaws/Sampling/DESIGN.md",
                    "Physics/ContactPatches/DESIGN.md",
                    "Physics/ContactPatches/Hydroelastic/DESIGN.md",
                    "Physics/ContactPatches/PlanePatches/DESIGN.md",
                    "Physics/ContactPatches/PressureFields/DESIGN.md",
                    "Physics/ContactResponse/DESIGN.md",
                    "Physics/ContactResponse/ImplicitNormal/DESIGN.md",
                    "Physics/ContactResponse/WitnessPorts/DESIGN.md",
                    "Physics/DESIGN.md",
                    "Physics/DeformingContact/ContactTransactions/DESIGN.md",
                    "Physics/DeformingContact/DESIGN.md",
                    "Physics/DeformingContact/MaterialGeometry/DESIGN.md",
                    "Physics/DeformingContact/WitnessForces/DESIGN.md",
                    "Physics/Dynamics/DESIGN.md",
                    "Physics/Dynamics/DenseDynamics/DESIGN.md",
                    "Physics/Dynamics/RigidEquations/DESIGN.md",
                    "Physics/Flexible/Beams/DESIGN.md",
                    "Physics/Flexible/DESIGN.md",
                    "Physics/Flexible/Refinement/DESIGN.md",
                    "Physics/Flexible/Attachments/DESIGN.md",
                    "Physics/Flexible/Hexahedra/DESIGN.md",
                    "Physics/Flexible/Mesh/DESIGN.md",
                    "Physics/Flexible/Tetrahedra/DESIGN.md",
                    "Physics/Fluids/ChannelDiscretization/DESIGN.md",
                    "Physics/Fluids/Continuation/DESIGN.md",
                    "Physics/Fluids/DESIGN.md",
                    "Physics/Fluids/PlanarContinuation/DESIGN.md",
                    "Physics/Fluids/PlanarProjection/DESIGN.md",
                    "Physics/Fluids/ViscousEvolution/DESIGN.md",
                    "Physics/Fluids/SpatialProjection/DESIGN.md",
                    "Physics/Granular/DESIGN.md",
                    "Physics/Granular/RuntimeContinuation/DESIGN.md",
                    "Physics/Granular/NeighborContacts/DESIGN.md",
                    "Physics/Granular/ParticleEvolution/DESIGN.md",
                    "Physics/Granular/ParticleState/DESIGN.md",
                    "Physics/Granular/Replay/DESIGN.md",
                    "Physics/Loads/CableRouting/DESIGN.md",
                    "Physics/Loads/CustomLaws/DESIGN.md",
                    "Physics/Loads/DESIGN.md",
                    "Physics/Loads/ForcePorts/DESIGN.md",
                    "Physics/Loads/PassiveLaws/DESIGN.md",
                    "Physics/Materials/Constitutive/DESIGN.md",
                    "Physics/Materials/DESIGN.md",
                    "Physics/Materials/Elasticity/DESIGN.md",
                    "Physics/Materials/Plasticity/DESIGN.md",
                    "Physics/Mechanisms/AcceptedTransitions/DESIGN.md",
                    "Physics/Mechanisms/ClosedLoopReactionPaths/DESIGN.md",
                    "Physics/Mechanisms/AffineEvolution/DESIGN.md",
                    "Physics/Mechanisms/ConnectedSleep/DESIGN.md",
                    "Physics/Mechanisms/ConstrainedDynamics/DESIGN.md",
                    "Physics/Mechanisms/NonlinearEvolution/DESIGN.md",
                    "Physics/Mechanisms/ReactionPaths/DESIGN.md",
                    "Physics/Mechanisms/SleepContinuation/DESIGN.md",
                    "Physics/Mechanisms/StationaryLoads/DESIGN.md",
                    "Physics/Mechanisms/DESIGN.md",
                    "Physics/Mechanisms/SubtreeTransitions/DESIGN.md",
                    "Physics/Mechanisms/TopologyContinuation/DESIGN.md",
                    "Physics/Transmissions/CompliantPorts/DESIGN.md",
                    "Physics/Transmissions/DESIGN.md",
                    "Physics/Transmissions/ToothContacts/DESIGN.md",
                    "Physics/Transmissions/IdealNetworks/DESIGN.md",
                    "Physics/Transmissions/PortBindings/DESIGN.md",
                    "Physics/Materials/MaxwellRelaxation/DESIGN.md",
                    "Physics/Actuation/SealedLiquid/DESIGN.md",
                    "Physics/Actuation/PolytropicGas/DESIGN.md",
                    "Physics/Actuation/ExactMotor/DESIGN.md",
                    "Physics/Transmissions/CapstanFriction/DESIGN.md",
                    "Physics/Dynamics/GyroscopicRotors/DESIGN.md",
                    "Physics/Materials/Thermoelasticity/DESIGN.md",
                    "Physics/Fluids/SphereAddedInertia/DESIGN.md",
                    "Physics/Loads/DahlFriction/DESIGN.md",
                    "Physics/Loads/ExponentialSpring/DESIGN.md",
                    "Physics/Loads/FiniteExtensionSpring/DESIGN.md",
                    "Physics/Loads/TabulatedSpring/DESIGN.md",
                    "Physics/Loads/PowerLawDamper/DESIGN.md",
                    "Physics/Loads/RegularizedYieldDamper/DESIGN.md",
                    "Physics/Loads/StribeckFriction/DESIGN.md",
                    "Physics/Loads/TabulatedDamper/DESIGN.md",
                    "Physics/Materials/KelvinVoigt/DESIGN.md",
                    "Physics/Materials/OrthotropicElasticity/DESIGN.md",
                    "Physics/Materials/StandardLinearSolid/DESIGN.md",
                    "Physics/Materials/BurgersCreep/DESIGN.md",
                    "Physics/Materials/NeoHookean/DESIGN.md",
                    "Physics/Materials/InvariantHyperelasticity/DESIGN.md",
                    "Physics/Transmissions/NonlinearKinematics/DESIGN.md",
                    "Physics/Actuation/HydraulicElements/DESIGN.md",
                ],
                linkerSettings: [.linkedLibrary("swiftUnicodeDataTables", .when(platforms: [.wasi], traits: ["EmbeddedUnicode"]))]),
        .target(name: "ParticleFlowsQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/ParticleFlowsQualification", exclude: ["DESIGN.md", "ParticleFlowsQualification.swift", "ParticleFlowsQualificationTests.swift"]),
        .executableTarget(name: "ParticleFlowsPublicVerification", dependencies: ["ParticleFlowsQualificationSupport"], path: "Verification/ParticleFlowsQualification", exclude: ["DESIGN.md", "ParticleFlowsQualificationError.swift", "ParticleFlowsQualificationFixture.swift", "ParticleFlowsQualificationCases.swift", "ParticleFlowsQualificationTests.swift"]),
        .testTarget(name: "MechanicsParticleFlowsTests", dependencies: ["ParticleFlowsQualificationSupport"], path: "Verification/ParticleFlowsQualification", exclude: ["DESIGN.md", "ParticleFlowsQualification.swift", "ParticleFlowsQualificationError.swift", "ParticleFlowsQualificationFixture.swift", "ParticleFlowsQualificationCases.swift"]),
        .target(name: "SpatialProjectionQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/SpatialProjectionQualification", exclude: ["DESIGN.md", "SpatialProjectionQualification.swift", "SpatialProjectionQualificationTests.swift"], sources: ["SpatialProjectionQualificationCases.swift", "SpatialProjectionQualificationCounter.swift", "SpatialProjectionQualificationError.swift", "SpatialProjectionQualificationFixture.swift", "SpatialProjectionQualificationPressureFault.swift"]),
        .executableTarget(name: "SpatialProjectionPublicVerification", dependencies: ["SpatialProjectionQualificationSupport"], path: "Verification/SpatialProjectionQualification", exclude: ["DESIGN.md", "SpatialProjectionQualificationCases.swift", "SpatialProjectionQualificationCounter.swift", "SpatialProjectionQualificationError.swift", "SpatialProjectionQualificationFixture.swift", "SpatialProjectionQualificationPressureFault.swift", "SpatialProjectionQualificationTests.swift"], sources: ["SpatialProjectionQualification.swift"]),
        .testTarget(name: "MechanicsSpatialProjectionTests", dependencies: ["SpatialProjectionQualificationSupport"], path: "Verification/SpatialProjectionQualification", exclude: ["DESIGN.md", "SpatialProjectionQualification.swift", "SpatialProjectionQualificationCases.swift", "SpatialProjectionQualificationCounter.swift", "SpatialProjectionQualificationError.swift", "SpatialProjectionQualificationFixture.swift", "SpatialProjectionQualificationPressureFault.swift"], sources: ["SpatialProjectionQualificationTests.swift"]),
        .target(name: "LinearEstimationQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/LinearEstimationQualification",
                exclude: ["DESIGN.md", "LinearEstimationQualificationRunner.swift", "LinearEstimationQualificationTests.swift"], sources: ["LinearEstimationQualificationCases.swift", "LinearEstimationQualificationError.swift", "LinearEstimationQualificationFixtures.swift", "LinearEstimationQualificationNativeCases.swift"]),
        .executableTarget(name: "LinearEstimationPublicVerification", dependencies: ["LinearEstimationQualificationSupport"], path: "Verification/LinearEstimationQualification",
                exclude: ["DESIGN.md", "LinearEstimationQualificationCases.swift", "LinearEstimationQualificationError.swift", "LinearEstimationQualificationFixtures.swift", "LinearEstimationQualificationNativeCases.swift", "LinearEstimationQualificationTests.swift"], sources: ["LinearEstimationQualificationRunner.swift"]),
        .testTarget(name: "MechanicsLinearEstimationTests", dependencies: ["LinearEstimationQualificationSupport"], path: "Verification/LinearEstimationQualification",
                exclude: ["DESIGN.md", "LinearEstimationQualificationCases.swift", "LinearEstimationQualificationError.swift", "LinearEstimationQualificationFixtures.swift", "LinearEstimationQualificationNativeCases.swift", "LinearEstimationQualificationRunner.swift"], sources: ["LinearEstimationQualificationTests.swift"]),
        .target(name: "SpatialBeamsQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/SpatialBeamsQualification",
                exclude: ["DESIGN.md", "SpatialBeamsQualification.swift", "SpatialBeamsQualificationTests.swift"], sources: ["SpatialBeamsCancellationCounter.swift", "SpatialBeamsQualificationCase.swift", "SpatialBeamsQualificationCases.swift", "SpatialBeamsQualificationError.swift", "SpatialBeamsQualificationFixtures.swift", "SpatialBeamsQualifying.swift"]),
        .executableTarget(name: "SpatialBeamsPublicVerification", dependencies: ["SpatialBeamsQualificationSupport"], path: "Verification/SpatialBeamsQualification",
                exclude: ["DESIGN.md", "SpatialBeamsQualificationTests.swift", "SpatialBeamsCancellationCounter.swift", "SpatialBeamsQualificationCase.swift", "SpatialBeamsQualificationCases.swift", "SpatialBeamsQualificationError.swift", "SpatialBeamsQualificationFixtures.swift", "SpatialBeamsQualifying.swift"], sources: ["SpatialBeamsQualification.swift"]),
        .testTarget(name: "MechanicsSpatialBeamsTests", dependencies: ["SpatialBeamsQualificationSupport"], path: "Verification/SpatialBeamsQualification",
                exclude: ["DESIGN.md", "SpatialBeamsQualification.swift", "SpatialBeamsCancellationCounter.swift", "SpatialBeamsQualificationCase.swift", "SpatialBeamsQualificationCases.swift", "SpatialBeamsQualificationError.swift", "SpatialBeamsQualificationFixtures.swift", "SpatialBeamsQualifying.swift"], sources: ["SpatialBeamsQualificationTests.swift"]),
        .target(name: "HydroelasticQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/HydroelasticQualification", exclude: ["DESIGN.md", "HydroelasticQualification.swift", "HydroelasticQualificationTests.swift"], sources: ["HydroelasticCancellationCounter.swift", "HydroelasticQualificationCase.swift", "HydroelasticQualificationCases.swift", "HydroelasticQualificationError.swift", "HydroelasticQualificationFixtures.swift", "HydroelasticQualifying.swift"]),
        .executableTarget(name: "HydroelasticPublicVerification", dependencies: ["HydroelasticQualificationSupport"], path: "Verification/HydroelasticQualification", exclude: ["DESIGN.md", "HydroelasticCancellationCounter.swift", "HydroelasticQualificationCase.swift", "HydroelasticQualificationCases.swift", "HydroelasticQualificationError.swift", "HydroelasticQualificationFixtures.swift", "HydroelasticQualificationTests.swift", "HydroelasticQualifying.swift"], sources: ["HydroelasticQualification.swift"]),
        .testTarget(name: "MechanicsHydroelasticTests", dependencies: ["SwiftMechanics", "HydroelasticQualificationSupport"], path: "Verification/HydroelasticQualification", exclude: ["DESIGN.md", "HydroelasticCancellationCounter.swift", "HydroelasticQualification.swift", "HydroelasticQualificationCase.swift", "HydroelasticQualificationCases.swift", "HydroelasticQualificationError.swift", "HydroelasticQualificationFixtures.swift", "HydroelasticQualifying.swift"], sources: ["HydroelasticQualificationTests.swift"]),
        .target(name: "TriangleMeshesQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/TriangleMeshesQualification", exclude: ["DESIGN.md", "TriangleMeshesQualification.swift", "TriangleMeshesQualificationTests.swift"]),
        .executableTarget(name: "TriangleMeshesPublicVerification", dependencies: ["TriangleMeshesQualificationSupport"], path: "Verification/TriangleMeshesQualification", exclude: ["DESIGN.md", "TriangleMeshesQualificationError.swift", "TriangleMeshesQualificationFixture.swift", "TriangleMeshesQualificationCases.swift", "TriangleMeshesQualificationTests.swift"]),
        .testTarget(name: "MechanicsTriangleMeshesTests", dependencies: ["TriangleMeshesQualificationSupport"], path: "Verification/TriangleMeshesQualification", exclude: ["DESIGN.md", "TriangleMeshesQualification.swift", "TriangleMeshesQualificationError.swift", "TriangleMeshesQualificationFixture.swift", "TriangleMeshesQualificationCases.swift"]),
        .executableTarget(name: "CoreVerification", dependencies: ["SwiftMechanics"], path: "Verification/CoreVerification", exclude: ["DESIGN.md"]),
        .executableTarget(name: "FoundationVerification", dependencies: ["SwiftMechanics"], path: "Verification/FoundationVerification",
                          exclude: ["DESIGN.md", "IslandSleepProbeContext.swift", "IslandSleepVerification.swift", "ConstrainedSleepProbeContext.swift", "ConstrainedSleepVerification.swift"]),
        .target(name: "TireLawsQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/TireLawsQualification",
                exclude: ["DESIGN.md", "TireLawsQualificationRunner.swift", "TireLawsQualificationTests.swift"], sources: ["TireLawsQualificationCases.swift", "TireLawsQualificationFixtures.swift", "TireLawsQualificationError.swift", "TireLawsQualificationNativeCases.swift"]),
        .executableTarget(name: "TireLawsPublicVerification", dependencies: ["TireLawsQualificationSupport"], path: "Verification/TireLawsQualification",
                exclude: ["DESIGN.md", "TireLawsQualificationCases.swift", "TireLawsQualificationError.swift", "TireLawsQualificationFixtures.swift", "TireLawsQualificationNativeCases.swift", "TireLawsQualificationTests.swift"], sources: ["TireLawsQualificationRunner.swift"]),
        .testTarget(name: "MechanicsTireLawsTests", dependencies: ["TireLawsQualificationSupport"], path: "Verification/TireLawsQualification",
                exclude: ["DESIGN.md", "TireLawsQualificationCases.swift", "TireLawsQualificationError.swift", "TireLawsQualificationFixtures.swift", "TireLawsQualificationNativeCases.swift", "TireLawsQualificationRunner.swift"], sources: ["TireLawsQualificationTests.swift"]),
        .target(name: "VehicleLawsQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/VehicleLawsQualification",
                exclude: ["DESIGN.md", "VehicleLawsQualification.swift", "VehicleLawsQualificationTests.swift"], sources: ["VehicleLawQualificationCases.swift", "VehicleLawQualificationError.swift", "VehicleLawQualificationFixtures.swift"]),
        .executableTarget(name: "VehicleLawsPublicVerification", dependencies: ["VehicleLawsQualificationSupport"], path: "Verification/VehicleLawsQualification",
                exclude: ["DESIGN.md", "VehicleLawQualificationCases.swift", "VehicleLawQualificationError.swift", "VehicleLawQualificationFixtures.swift", "VehicleLawsQualificationTests.swift"], sources: ["VehicleLawsQualification.swift"]),
        .testTarget(name: "MechanicsVehicleLawsTests", dependencies: ["VehicleLawsQualificationSupport"], path: "Verification/VehicleLawsQualification",
                exclude: ["DESIGN.md", "VehicleLawQualificationCases.swift", "VehicleLawQualificationError.swift", "VehicleLawQualificationFixtures.swift", "VehicleLawsQualification.swift"], sources: ["VehicleLawsQualificationTests.swift"]),
        .testTarget(name: "MechanicsControlTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsSensorPipelineTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsContactRangeObservationTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsIslandDynamicsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsParameterIdentificationTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsConstrainedImpactTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsObservationsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsTimeParameterizationTests", dependencies: ["SwiftMechanics"], path: "Verification/TimeParameterizationQualification",
                    exclude: ["DESIGN.md", "TimeParameterizationQualification.swift"]),
        .testTarget(name: "MechanicsSixHydraulicTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsSixTransmissionTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsSixHyperelasticTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsThreeConstitutiveTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsNineAdditionalTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsThreeAdditionalTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsAdditionalModelsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsEnvironmentalLoadsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsLinearProgramsTests", dependencies: ["SwiftMechanics"], path: "Verification/LinearProgramsQualification",
                    exclude: ["DESIGN.md", "LinearProgramsQualification.swift"]),
        .testTarget(name: "MechanicsHexahedraTests", dependencies: ["SwiftMechanics"], path: "Verification/HexahedraQualification",
                    exclude: ["DESIGN.md", "HexahedraQualification.swift"]),
        .testTarget(name: "MechanicsFrictionalImpulseTests", dependencies: ["SwiftMechanics"], path: "Verification/FrictionalImpulseQualification",
                    exclude: ["DESIGN.md", "FrictionalImpulseQualification.swift"]),
        .testTarget(name: "MechanicsAttachmentsTests", dependencies: ["SwiftMechanics"], path: "Verification/AttachmentsQualification",
                    exclude: ["DESIGN.md", "AttachmentsQualification.swift"]),
        .testTarget(name: "MechanicsConvexQueriesTests", dependencies: ["SwiftMechanics"], path: "Verification/ConvexQueriesQualification",
                    exclude: ["DESIGN.md", "ConvexQueriesQualification.swift"]),
        .testTarget(name: "MechanicsURDFTests", dependencies: ["SwiftMechanics"], path: "Verification/URDFQualification",
                    exclude: ["DESIGN.md", "URDFQualification.swift"]),
        .testTarget(name: "MechanicsAffineRigidGravityTests", dependencies: ["SwiftMechanics"], path: "Verification/AffineRigidGravityQualification",
                    exclude: ["DESIGN.md", "AffineRigidGravityQualification.swift"]),
        .testTarget(name: "MechanicsExternalCommandsTests", dependencies: ["SwiftMechanics"], path: "Verification/ExternalCommandsQualification",
                    exclude: ["DESIGN.md", "ExternalCommandsQualification.swift"]),
        .testTarget(name: "MechanicsJointStopsTests", dependencies: ["SwiftMechanics"], path: "Verification/JointStopsQualification",
                    exclude: ["DESIGN.md", "JointStopsQualification.swift"]),
        .testTarget(name: "MechanicsMJCFTests", dependencies: ["SwiftMechanics"], path: "Verification/MJCFQualification",
                    exclude: ["DESIGN.md", "MJCFQualification.swift"]),
        .testTarget(name: "MechanicsXMLTests", dependencies: ["SwiftMechanics"], path: "Verification/XMLQualification",
                    exclude: ["DESIGN.md", "XMLQualification.swift"]),
        .testTarget(name: "MechanicsCoreTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsModelTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsMaterialsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsNumericsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsNonlinearTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsComplementarityTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsJointsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsLoadsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsCompilerTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsCollisionTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsDynamicsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsFlexibleTests", dependencies: ["SwiftMechanics"], exclude: ["Beams/DESIGN.md", "DESIGN.md"]),
        .testTarget(name: "MechanicsContactLawsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsContactCurrentTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsRuntimeTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsContactResponseTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsIntegrationTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsConstraintsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsGeometricConstraintTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsActuationTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsHybridTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsTransmissionsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsEquilibriumTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsContactPatchesTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsDeformingContactTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsStructuralAnalysisTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsNonlinearStabilityTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsDerivativesTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsFluidsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsMechanismsTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsNonlinearMechanismTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsSleepMechanismTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsReactionPathTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsClosedLoopReactionTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsTopologyReleaseTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsGranularTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsFluidsRuntimeTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsFluidsProjectionTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsOptimizationTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsContactDerivativeTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsNonlinearOptimizationTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsGranularRuntimeTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsExchangeTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .target(name: "StructuralAuthoringQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/StructuralAuthoringQualification",
                    exclude: ["DESIGN.md", "StructuralAuthoringQualification.swift", "StructuralAuthoringQualificationTests.swift"], sources: ["StructuralAuthoringQualificationCases.swift", "StructuralAuthoringQualificationError.swift", "StructuralAuthoringQualificationFixtures.swift", "StructuralAuthoringQualificationMotion.swift"]),
        .executableTarget(name: "StructuralAuthoringPublicVerification", dependencies: ["SwiftMechanics", "StructuralAuthoringQualificationSupport"], path: "Verification/StructuralAuthoringQualification",
                    exclude: ["DESIGN.md", "StructuralAuthoringQualificationCases.swift", "StructuralAuthoringQualificationError.swift", "StructuralAuthoringQualificationFixtures.swift", "StructuralAuthoringQualificationMotion.swift", "StructuralAuthoringQualificationTests.swift"], sources: ["StructuralAuthoringQualification.swift"]),
        .testTarget(name: "MechanicsStructuralAuthoringTests", dependencies: ["SwiftMechanics", "StructuralAuthoringQualificationSupport"], path: "Verification/StructuralAuthoringQualification",
                    exclude: ["DESIGN.md", "StructuralAuthoringQualification.swift", "StructuralAuthoringQualificationCases.swift", "StructuralAuthoringQualificationError.swift", "StructuralAuthoringQualificationFixtures.swift", "StructuralAuthoringQualificationMotion.swift"], sources: ["StructuralAuthoringQualificationTests.swift"]),
        .testTarget(name: "SwiftMechanicsMachineTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsComplexSpectrumTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsDampedSpectrumTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsToothContactTests", dependencies: ["SwiftMechanics"], exclude: ["DESIGN.md"]),
        .testTarget(name: "MechanicsTaskSpaceTests", dependencies: ["SwiftMechanics"], path: "Verification/TaskSpaceQualification",
                    exclude: ["DESIGN.md", "TaskSpaceQualification.swift"]),
        .testTarget(name: "MechanicsRollingRelationsTests", dependencies: ["SwiftMechanics"], path: "Verification/RollingRelationsQualification",
                    exclude: ["DESIGN.md", "RollingRelationsQualification.swift"]),
        .target(name: "ArticulatedDynamicsQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/ArticulatedDynamicsQualification",
                exclude: ["DESIGN.md", "ArticulatedDynamicsQualificationRunner.swift", "ArticulatedDynamicsQualificationTests.swift"], sources: ["ArticulatedDynamicsQualificationCases.swift", "ArticulatedDynamicsQualificationError.swift", "ArticulatedDynamicsQualificationFixtures.swift", "ArticulatedDynamicsQualificationNativeCases.swift"]),
        .executableTarget(name: "ArticulatedDynamicsPublicVerification", dependencies: ["ArticulatedDynamicsQualificationSupport"], path: "Verification/ArticulatedDynamicsQualification",
                exclude: ["DESIGN.md", "ArticulatedDynamicsQualificationCases.swift", "ArticulatedDynamicsQualificationError.swift", "ArticulatedDynamicsQualificationFixtures.swift", "ArticulatedDynamicsQualificationNativeCases.swift", "ArticulatedDynamicsQualificationTests.swift"], sources: ["ArticulatedDynamicsQualificationRunner.swift"]),
        .testTarget(name: "MechanicsArticulatedDynamicsTests", dependencies: ["ArticulatedDynamicsQualificationSupport"], path: "Verification/ArticulatedDynamicsQualification",
                exclude: ["DESIGN.md", "ArticulatedDynamicsQualificationCases.swift", "ArticulatedDynamicsQualificationError.swift", "ArticulatedDynamicsQualificationFixtures.swift", "ArticulatedDynamicsQualificationNativeCases.swift", "ArticulatedDynamicsQualificationRunner.swift"], sources: ["ArticulatedDynamicsQualificationTests.swift"]),
        .testTarget(name: "MechanicsGeometryParametersTests", dependencies: ["SwiftMechanics"], path: "Verification/GeometryParametersQualification",
                    exclude: ["DESIGN.md", "GeometryParametersQualification.swift"]),
        .testTarget(name: "MechanicsPoseIKTests", dependencies: ["SwiftMechanics"], path: "Verification/PoseIKQualification",
                    exclude: ["DESIGN.md", "PoseIKQualification.swift"]),
        .target(name: "NonlinearEstimationQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/NonlinearEstimationQualification",
                exclude: ["DESIGN.md", "NonlinearEstimationQualification.swift", "NonlinearEstimationQualificationTests.swift"], sources: ["NonlinearEstimationQualificationCases.swift", "NonlinearEstimationQualificationError.swift", "NonlinearEstimationQualificationFixtures.swift", "NonlinearEstimationQualificationOracle.swift"]),
        .executableTarget(name: "NonlinearEstimationPublicVerification", dependencies: ["NonlinearEstimationQualificationSupport"], path: "Verification/NonlinearEstimationQualification",
                exclude: ["DESIGN.md", "NonlinearEstimationQualificationCases.swift", "NonlinearEstimationQualificationError.swift", "NonlinearEstimationQualificationFixtures.swift", "NonlinearEstimationQualificationOracle.swift", "NonlinearEstimationQualificationTests.swift"], sources: ["NonlinearEstimationQualification.swift"]),
        .testTarget(name: "MechanicsNonlinearEstimationTests", dependencies: ["SwiftMechanics", "NonlinearEstimationQualificationSupport"], path: "Verification/NonlinearEstimationQualification",
                exclude: ["DESIGN.md", "NonlinearEstimationQualification.swift", "NonlinearEstimationQualificationCases.swift", "NonlinearEstimationQualificationError.swift", "NonlinearEstimationQualificationFixtures.swift", "NonlinearEstimationQualificationOracle.swift"], sources: ["NonlinearEstimationQualificationTests.swift"]),
        .target(name: "SDFQualificationSupport", dependencies: ["SwiftMechanics"], path: "Verification/SDFQualification",
                exclude: ["DESIGN.md", "SDFQualification.swift", "SDFQualificationTests.swift"], sources: ["SDFQualificationCases.swift", "SDFQualificationError.swift", "SDFQualificationFixtures.swift"]),
        .executableTarget(name: "SDFPublicVerification", dependencies: ["SDFQualificationSupport"], path: "Verification/SDFQualification",
                exclude: ["DESIGN.md", "SDFQualificationTests.swift", "SDFQualificationCases.swift", "SDFQualificationError.swift", "SDFQualificationFixtures.swift"], sources: ["SDFQualification.swift"]),
        .testTarget(name: "MechanicsSDFTests", dependencies: ["SwiftMechanics", "SDFQualificationSupport"], path: "Verification/SDFQualification",
                exclude: ["DESIGN.md", "SDFQualification.swift", "SDFQualificationCases.swift", "SDFQualificationError.swift", "SDFQualificationFixtures.swift"], sources: ["SDFQualificationTests.swift"]),
    ],
    swiftLanguageModes: [.v6]
)
