/// Real lookup over caller-supplied immutable original records. No files, network, generated bytes or fallback.
public struct MemoryAssetProvider: AssetProviding {
    public let records: [AssetProviderRecord]
    public init(records: [AssetProviderRecord]) { self.records = records }
    public func read(address: AssetAddress, limits: AssetReadLimits,
                     work: inout AssetProviderWork) throws(AssetProviderFailure) -> AssetProviderRecord {
        try work.beginRead()
        guard records.count <= work.policy.maximumInventoryRecords else { throw .limit(.providerInventory, work.policy.maximumInventoryRecords) }
        var selected: AssetProviderRecord? = nil
        for record in records {
            try work.charge(1)
            let base = try same(record.address.base, address.base, limit: limits.maximumStringBytes, work: &work)
            let path = try same(record.address.relativePath, address.relativePath, limit: limits.maximumStringBytes, work: &work)
            if base && path {
                guard selected == nil else { throw .ambiguous }
                selected = record
            }
        }
        guard let selected else { throw .missing }
        guard selected.dependencies.count <= limits.maximumDependencies else { throw .limit(.edges, limits.maximumDependencies) }
        var metadata = 0
        try text(selected.address.base, total: &metadata, limits: limits, work: &work)
        try text(selected.address.relativePath, total: &metadata, limits: limits, work: &work)
        try text(selected.asset.key, total: &metadata, limits: limits, work: &work)
        try text(selected.asset.format, total: &metadata, limits: limits, work: &work)
        try text(selected.asset.provenance.source, total: &metadata, limits: limits, work: &work)
        for dependency in selected.dependencies {
            try text(dependency.base, total: &metadata, limits: limits, work: &work)
            try text(dependency.relativePath, total: &metadata, limits: limits, work: &work)
        }
        // Existing immutable backing is retained, not copied. Count the source span that this read can deliver.
        let available = min(limits.maximumBytes, work.remainingBytes)
        let consumed = min(selected.asset.bytes.count, available)
        try work.consumeBytes(consumed)
        guard selected.asset.bytes.count <= limits.maximumBytes else { throw .limit(.assetBytes, limits.maximumBytes) }
        guard selected.asset.bytes.count == consumed else { throw .limit(.providerBytes, work.policy.maximumBytesRead) }
        try work.checkCancellation()
        return selected
    }
    private func same(_ a: String, _ b: String, limit: Int, work: inout AssetProviderWork) throws(AssetProviderFailure) -> Bool {
        guard a.utf8.count <= limit, b.utf8.count <= limit else { throw .limit(.stringBytes, limit) }
        try work.charge(a.utf8.count); try work.charge(b.utf8.count)
        return a.utf8.elementsEqual(b.utf8)
    }
    private func text(_ value: String, total: inout Int, limits: AssetReadLimits,
                      work: inout AssetProviderWork) throws(AssetProviderFailure) {
        guard value.utf8.count <= limits.maximumStringBytes else { throw .limit(.stringBytes, limits.maximumStringBytes) }
        let (next, overflow) = total.addingReportingOverflow(value.utf8.count)
        guard !overflow else { throw .arithmeticOverflow }
        guard next <= limits.maximumMetadataBytes else { throw .limit(.metadataBytes, limits.maximumMetadataBytes) }
        try work.charge(value.utf8.count); total = next
    }
}
