internal enum ToothMaterialAcceptance {
    static func current(_ supplied: ContactCurrentResponse, _ original: ContactCurrentResponse,
                        work: inout ToothContactWork) throws(ToothContactError) {
        try work.charge(512)
        guard supplied.forceOnB == original.forceOnB,
              supplied.coupleOnB == original.coupleOnB,
              supplied.compressiveNormalForce == original.compressiveNormalForce,
              supplied.cohesiveNormalForce == original.cohesiveNormalForce,
              supplied.tangentialForceFirst == original.tangentialForceFirst,
              supplied.tangentialForceSecond == original.tangentialForceSecond,
              supplied.normalStoredEnergy == original.normalStoredEnergy,
              supplied.tangentialStoredEnergy == original.tangentialStoredEnergy,
              supplied.cohesivePotentialEnergy == original.cohesivePotentialEnergy,
              supplied.completeCohesiveSeparationWork == original.completeCohesiveSeparationWork,
              supplied.normalDissipationPower == original.normalDissipationPower,
              supplied.resistanceDissipationPower == original.resistanceDissipationPower,
              supplied.relativeMechanicalPower == original.relativeMechanicalPower,
              supplied.originalPowerResidual == original.originalPowerResidual,
              supplied.elasticNormalForce == original.elasticNormalForce,
              supplied.elasticPotentialRatePower == original.elasticPotentialRatePower,
              supplied.staticFrictionConeUtilization == original.staticFrictionConeUtilization,
              supplied.originalRatePowerResidual == original.originalRatePowerResidual,
              supplied.acceptedHistory == original.acceptedHistory,
              supplied.derivatives.normalForcePenetrationDerivative == original.derivatives.normalForcePenetrationDerivative,
              supplied.derivatives.normalForceVelocityDerivative == original.derivatives.normalForceVelocityDerivative,
              supplied.derivatives.normalIsDifferentiable == original.derivatives.normalIsDifferentiable,
              supplied.derivatives.cohesiveForceSeparationDerivative == original.derivatives.cohesiveForceSeparationDerivative,
              supplied.derivatives.cohesionIsDifferentiable == original.derivatives.cohesionIsDifferentiable,
              supplied.derivatives.tangentialForceBristleDerivative == original.derivatives.tangentialForceBristleDerivative,
              supplied.derivatives.rollingFirstAngularDerivative == original.derivatives.rollingFirstAngularDerivative,
              supplied.derivatives.rollingCrossAngularDerivative == original.derivatives.rollingCrossAngularDerivative,
              supplied.derivatives.rollingSecondAngularDerivative == original.derivatives.rollingSecondAngularDerivative,
              supplied.derivatives.spinningAngularDerivative == original.derivatives.spinningAngularDerivative,
              supplied.derivatives.coupleCompressiveLoadDerivative == original.derivatives.coupleCompressiveLoadDerivative else { throw .invalidSupplierOutput }
    }
    static func trial(_ supplied: ContactResponse, _ original: ContactResponse,
                      work: inout ToothContactWork) throws(ToothContactError) {
        try work.charge(512)
        guard supplied.forceOnB == original.forceOnB,
              supplied.coupleOnB == original.coupleOnB,
              supplied.compressiveNormalForce == original.compressiveNormalForce,
              supplied.cohesiveNormalForce == original.cohesiveNormalForce,
              supplied.tangentialForceFirst == original.tangentialForceFirst,
              supplied.tangentialForceSecond == original.tangentialForceSecond,
              supplied.normalStoredEnergy == original.normalStoredEnergy,
              supplied.tangentialStoredEnergy == original.tangentialStoredEnergy,
              supplied.cohesivePotentialEnergy == original.cohesivePotentialEnergy,
              supplied.completeCohesiveSeparationWork == original.completeCohesiveSeparationWork,
              supplied.normalDissipationPower == original.normalDissipationPower,
              supplied.resistanceDissipationPower == original.resistanceDissipationPower,
              supplied.relativeMechanicalPower == original.relativeMechanicalPower,
              supplied.originalPowerResidual == original.originalPowerResidual,
              supplied.normalForcePenetrationDerivative == original.normalForcePenetrationDerivative,
              supplied.normalForceVelocityDerivative == original.normalForceVelocityDerivative,
              supplied.tangentialDissipationEnergy == original.tangentialDissipationEnergy,
              supplied.frictionConeUtilization == original.frictionConeUtilization,
              supplied.frictionRegime == original.frictionRegime,
              supplied.originalTangentialEnergyResidual == original.originalTangentialEnergyResidual,
              supplied.acceptedHistorySequence == original.acceptedHistorySequence,
              supplied.trialHistory == original.trialHistory else { throw .invalidSupplierOutput }
    }
    static func endpoint(_ trial: ContactResponse, _ current: ContactCurrentResponse,
                         work: inout ToothContactWork) throws(ToothContactError) {
        try work.charge(256)
        guard trial.trialHistory == current.acceptedHistory,
              trial.forceOnB == current.forceOnB,
              trial.coupleOnB == current.coupleOnB,
              trial.compressiveNormalForce == current.compressiveNormalForce,
              trial.cohesiveNormalForce == current.cohesiveNormalForce,
              trial.tangentialForceFirst == current.tangentialForceFirst,
              trial.tangentialForceSecond == current.tangentialForceSecond,
              trial.normalStoredEnergy == current.normalStoredEnergy,
              trial.tangentialStoredEnergy == current.tangentialStoredEnergy,
              trial.cohesivePotentialEnergy == current.cohesivePotentialEnergy,
              trial.completeCohesiveSeparationWork == current.completeCohesiveSeparationWork,
              trial.normalDissipationPower == current.normalDissipationPower,
              trial.resistanceDissipationPower == current.resistanceDissipationPower,
              trial.relativeMechanicalPower == current.relativeMechanicalPower,
              trial.originalPowerResidual == current.originalPowerResidual else { throw .invalidSupplierOutput }
    }
}
