public enum SIUnits {
    public static let metre = UnitDefinition(validatedSymbol: "m", dimension: .length, scale: 1, offset: 0)
    public static let millimetre = UnitDefinition(validatedSymbol: "mm", dimension: .length, scale: 0.001, offset: 0)
    public static let centimetre = UnitDefinition(validatedSymbol: "cm", dimension: .length, scale: 0.01, offset: 0)
    public static let inch = UnitDefinition(validatedSymbol: "in", dimension: .length, scale: 0.0254, offset: 0)
    public static let foot = UnitDefinition(validatedSymbol: "ft", dimension: .length, scale: 0.3048, offset: 0)
    public static let kilogram = UnitDefinition(validatedSymbol: "kg", dimension: .mass, scale: 1, offset: 0)
    public static let gram = UnitDefinition(validatedSymbol: "g", dimension: .mass, scale: 0.001, offset: 0)
    public static let second = UnitDefinition(validatedSymbol: "s", dimension: .time, scale: 1, offset: 0)
    public static let millisecond = UnitDefinition(validatedSymbol: "ms", dimension: .time, scale: 0.001, offset: 0)
    public static let radian = UnitDefinition(validatedSymbol: "rad", dimension: .angle, scale: 1, offset: 0)
    public static let degree = UnitDefinition(validatedSymbol: "deg", dimension: .angle, scale: Double.pi / 180, offset: 0)
    public static let newton = UnitDefinition(validatedSymbol: "N", dimension: .force, scale: 1, offset: 0)
    public static let joule = UnitDefinition(validatedSymbol: "J", dimension: .energy, scale: 1, offset: 0)
    public static let newtonMetre = UnitDefinition(validatedSymbol: "N*m", dimension: .energy, scale: 1, offset: 0)
    public static let pascal = UnitDefinition(validatedSymbol: "Pa", dimension: .pressure, scale: 1, offset: 0)
    public static let ampere = UnitDefinition(validatedSymbol: "A", dimension: .electricCurrent, scale: 1, offset: 0)
    public static let volt = UnitDefinition(validatedSymbol: "V", dimension: .voltage, scale: 1, offset: 0)
    public static let ohm = UnitDefinition(validatedSymbol: "ohm", dimension: .resistance, scale: 1, offset: 0)
    public static let kelvin = UnitDefinition(validatedSymbol: "K", dimension: .temperature, scale: 1, offset: 0)
    public static let celsius = UnitDefinition(validatedSymbol: "degC", dimension: .temperature, scale: 1, offset: 273.15)
}
